In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import os
import numpy as np

In [2]:
import tensorflow
tensorflow.keras.__version__

'2.4.0'

In [3]:
file1 = pd.read_csv("student-mat.csv",sep=";",header=0)
file2 = pd.read_csv("student-por.csv",sep=";",header=0)

In [4]:
file1['subject'] = 'Math'


In [5]:
file1.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  freetime goout  Dalc  Walc  health absences  G1  G2  G3 subject  
0        3     4     1     1       3        6   5   6   6    Math  
1        3     3     1     1       3        4   5   5   6    Math  
2        3     2     2     3       3       10   7   8  10    Math  
3        2     2     1     1       5        2  15  14  15    Math  
4        3     2     1     2       5        4   6  10  10    Math  

[5 rows x 34 columns]

In [6]:
file2['subject'] = 'Por'

In [7]:
file2.head()

school sex  age address famsize Pstatus  Medu  Fedu     Mjob      Fjob  ...  \
0     GP   F   18       U     GT3       A     4     4  at_home   teacher  ...   
1     GP   F   17       U     GT3       T     1     1  at_home     other  ...   
2     GP   F   15       U     LE3       T     1     1  at_home     other  ...   
3     GP   F   15       U     GT3       T     4     2   health  services  ...   
4     GP   F   16       U     GT3       T     3     3    other     other  ...   

  freetime goout  Dalc  Walc  health absences  G1  G2  G3 subject  
0        3     4     1     1       3        4   0  11  11     Por  
1        3     3     1     1       3        2   9  11  11     Por  
2        3     2     2     3       3        6  12  13  12     Por  
3        2     2     1     1       5        0  14  14  14     Por  
4        3     2     1     2       5        0  11  13  13     Por  

[5 rows x 34 columns]

In [8]:
df = pd.concat([file1,file2])


In [9]:
df.reset_index(drop=True,inplace=True)

In [10]:
 df.to_csv("student-mat-por_combinedData.csv")

In [11]:
 df1 = pd.read_csv('student-mat-por_combinedData.csv')

In [12]:
df1

Unnamed: 0 school sex  age address famsize Pstatus  Medu  Fedu  \
0              0     GP   F   18       U     GT3       A     4     4   
1              1     GP   F   17       U     GT3       T     1     1   
2              2     GP   F   15       U     LE3       T     1     1   
3              3     GP   F   15       U     GT3       T     4     2   
4              4     GP   F   16       U     GT3       T     3     3   
...          ...    ...  ..  ...     ...     ...     ...   ...   ...   
1039        1039     MS   F   19       R     GT3       T     2     3   
1040        1040     MS   F   18       U     LE3       T     3     1   
1041        1041     MS   F   18       U     GT3       T     1     1   
1042        1042     MS   M   17       U     LE3       T     3     1   
1043        1043     MS   M   18       R     LE3       T     3     2   

          Mjob  ... freetime goout Dalc  Walc  health  absences  G1  G2  G3  \
0      at_home  ...        3     4    1     1       3         6   5   6   6   
1      at_home  ...        3     3    1     1       3         4   5   5   6   
2      at_home  ...        3     2    2     3       3        10   7   8  10   
3       health  ...        2     2    1     1       5         2  15  14  15   
4        other  ...        3     2    1     2       5         4   6  10  10   
...        ...  ...      ...   ...  ...   ...     ...       ...  ..  ..  ..   
1039  services  ...        4     2    1     2       5         4  10  11  10   
1040   teacher  ...        3     4    1     1       1         4  15  15  16   
1041     other  ...        1     1    1     1       5         6  11  12   9   
1042  services  ...        4     5    3     4       2         6  10  10  10   
1043  services  ...        4     1    3     4       5         4  10  11  11   

     subject  
0       Math  
1       Math  
2       Math  
3       Math  
4       Math  
...      ...  
1039     Por  
1040     Por  
1041     Por  
1042     Por  
1043     Por  

[1044 rows x 35 columns]

In [13]:
grade = []
for x in df["G3"]:

    if x > 15:
        grade.append(4)
    elif x >= 10:
        grade.append(3)
    elif x >= 5:
        grade.append(2)
    else:
        grade.append(1)
print(grade)

[2, 2, 3, 3, 3, 3, 3, 2, 4, 3, 2, 3, 3, 3, 4, 3, 3, 3, 2, 3, 3, 3, 4, 3, 2, 2, 3, 3, 3, 3, 3, 4, 4, 3, 3, 2, 4, 3, 3, 3, 3, 3, 4, 3, 2, 2, 3, 4, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 2, 4, 3, 3, 2, 2, 3, 3, 3, 2, 2, 4, 3, 3, 2, 3, 3, 3, 3, 3, 3, 2, 3, 3, 2, 3, 3, 2, 2, 3, 3, 2, 2, 4, 2, 3, 3, 3, 3, 3, 3, 2, 2, 4, 3, 2, 4, 3, 2, 4, 3, 4, 4, 3, 3, 4, 2, 4, 3, 3, 2, 3, 3, 3, 3, 3, 2, 3, 3, 2, 1, 4, 1, 1, 3, 3, 1, 1, 1, 1, 3, 3, 1, 2, 3, 3, 1, 3, 1, 3, 1, 3, 1, 3, 3, 1, 3, 2, 3, 3, 3, 3, 1, 2, 1, 3, 2, 3, 3, 4, 1, 3, 1, 4, 3, 1, 2, 2, 3, 2, 2, 3, 2, 3, 4, 2, 3, 3, 3, 3, 2, 3, 3, 2, 2, 3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 2, 3, 2, 2, 3, 3, 2, 2, 3, 3, 2, 3, 3, 1, 2, 2, 3, 2, 1, 4, 3, 3, 2, 3, 3, 2, 3, 3, 3, 2, 3, 2, 3, 3, 3, 3, 1, 3, 3, 1, 3, 1, 4, 3, 2, 2, 3, 2, 3, 2, 2, 3, 2, 3, 3, 3, 1, 4, 2, 3, 2, 1, 4, 3, 3, 3, 1, 2, 3, 3, 3, 3, 3, 2, 2, 2, 3, 2, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 4, 3, 3, 1, 2, 3, 4, 3, 3, 3, 4, 3, 3, 4, 2, 3, 3, 1, 3, 3, 3, 3, 3, 1, 2, 3, 3, 3, 2, 3, 3, 3, 3, 4, 3, 2, 3, 2, 3, 1, 

In [14]:
df["grade"] = grade
df

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0        GP   F   18       U     GT3       A     4     4   at_home   teacher   
1        GP   F   17       U     GT3       T     1     1   at_home     other   
2        GP   F   15       U     LE3       T     1     1   at_home     other   
3        GP   F   15       U     GT3       T     4     2    health  services   
4        GP   F   16       U     GT3       T     3     3     other     other   
...     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
1039     MS   F   19       R     GT3       T     2     3  services     other   
1040     MS   F   18       U     LE3       T     3     1   teacher  services   
1041     MS   F   18       U     GT3       T     1     1     other     other   
1042     MS   M   17       U     LE3       T     3     1  services  services   
1043     MS   M   18       R     LE3       T     3     2  services     other   

      ... goout Dalc  Walc  health  absences  G1  G2  G3 subject grade  
0     ...     4    1     1       3         6   5   6   6    Math     2  
1     ...     3    1     1       3         4   5   5   6    Math     2  
2     ...     2    2     3       3        10   7   8  10    Math     3  
3     ...     2    1     1       5         2  15  14  15    Math     3  
4     ...     2    1     2       5         4   6  10  10    Math     3  
...   ...   ...  ...   ...     ...       ...  ..  ..  ..     ...   ...  
1039  ...     2    1     2       5         4  10  11  10     Por     3  
1040  ...     4    1     1       1         4  15  15  16     Por     4  
1041  ...     1    1     1       5         6  11  12   9     Por     2  
1042  ...     5    3     4       2         6  10  10  10     Por     3  
1043  ...     1    3     4       5         4  10  11  11     Por     3  

[1044 rows x 35 columns]

In [15]:
new_df = df.drop(columns = ["G2","G1","G3"])
new_df

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
0        GP   F   18       U     GT3       A     4     4   at_home   teacher   
1        GP   F   17       U     GT3       T     1     1   at_home     other   
2        GP   F   15       U     LE3       T     1     1   at_home     other   
3        GP   F   15       U     GT3       T     4     2    health  services   
4        GP   F   16       U     GT3       T     3     3     other     other   
...     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
1039     MS   F   19       R     GT3       T     2     3  services     other   
1040     MS   F   18       U     LE3       T     3     1   teacher  services   
1041     MS   F   18       U     GT3       T     1     1     other     other   
1042     MS   M   17       U     LE3       T     3     1  services  services   
1043     MS   M   18       R     LE3       T     3     2  services     other   

      ... romantic famrel  freetime  goout  Dalc Walc health absences subject  \
0     ...       no      4         3      4     1    1      3        6    Math   
1     ...       no      5         3      3     1    1      3        4    Math   
2     ...       no      4         3      2     2    3      3       10    Math   
3     ...      yes      3         2      2     1    1      5        2    Math   
4     ...       no      4         3      2     1    2      5        4    Math   
...   ...      ...    ...       ...    ...   ...  ...    ...      ...     ...   
1039  ...       no      5         4      2     1    2      5        4     Por   
1040  ...       no      4         3      4     1    1      1        4     Por   
1041  ...       no      1         1      1     1    1      5        6     Por   
1042  ...       no      2         4      5     3    4      2        6     Por   
1043  ...       no      4         4      1     3    4      5        4     Por   

     grade  
0        2  
1        2  
2        3  
3        3  
4        3  
...    ...  
1039     3  
1040     4  
1041     2  
1042     3  
1043     3  

[1044 rows x 32 columns]

In [16]:
data = new_df.values
X = new_df.drop(columns =["grade"])
y = new_df['grade']
y

0       2
1       2
2       3
3       3
4       3
       ..
1039    3
1040    4
1041    2
1042    3
1043    3
Name: grade, Length: 1044, dtype: int64

In [17]:
cat_columns = ["school","sex","address","famsize","Pstatus","Mjob","Fjob","reason","guardian","schoolsup","famsup","paid","activities","nursery","higher","internet","romantic","subject"]
cat_columns2 = ["freetime","age","health","Walc","goout"]

cat_columns2

['freetime', 'age', 'health', 'Walc', 'goout']

In [18]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
label_encoder = LabelEncoder()

In [19]:
X= X[cat_columns2]
##X= X.apply(LabelEncoder().fit_transform)
X

freetime  age  health  Walc  goout
0            3   18       3     1      4
1            3   17       3     1      3
2            3   15       3     3      2
3            2   15       5     1      2
4            3   16       5     2      2
...        ...  ...     ...   ...    ...
1039         4   19       5     2      2
1040         3   18       1     1      4
1041         1   18       5     1      1
1042         4   17       2     4      5
1043         4   18       5     4      1

[1044 rows x 5 columns]

In [21]:
X2= X[cat_columns2]
X2= X2.apply(LabelEncoder().fit_transform)

In [23]:
#X2[["school","subject"]] = X2[["school","subject"]].apply(LabelEncoder().fit_transform)

In [24]:
print(X2)

      freetime  age  health  Walc  goout
0            2    3       2     0      3
1            2    2       2     0      2
2            2    0       2     2      1
3            1    0       4     0      1
4            2    1       4     1      1
...        ...  ...     ...   ...    ...
1039         3    4       4     1      1
1040         2    3       0     0      3
1041         0    3       4     0      0
1042         3    2       1     3      4
1043         3    3       4     3      0

[1044 rows x 5 columns]


In [69]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X2, y,test_size=0.1,random_state=50)


In [70]:
from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler().fit(X_train)

In [71]:
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [72]:
import sklearn
from tensorflow.keras.utils import to_categorical

In [73]:
y_train_categorical = to_categorical(y_train)
y_test_categorical = to_categorical(y_test)

In [74]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [75]:
model = Sequential()
model.add(Dense(units=100, activation='relu', input_dim=5))
model.add(Dense(units=100, activation='relu'))
model.add(Dense(units=100, activation='relu'))

model.add(Dense(units=5, activation='softmax'))

In [76]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_16 (Dense)             (None, 100)               600       
_________________________________________________________________
dense_17 (Dense)             (None, 100)               10100     
_________________________________________________________________
dense_18 (Dense)             (None, 100)               10100     
_________________________________________________________________
dense_19 (Dense)             (None, 5)                 505       
Total params: 21,305
Trainable params: 21,305
Non-trainable params: 0
_________________________________________________________________


In [77]:
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [84]:
model.fit(
    X_train_scaled,
    y_train_categorical,
    epochs=1000,
    shuffle=True,
    verbose=2
)

Epoch 1/1000
30/30 - 0s - loss: 0.4137 - accuracy: 0.7583
Epoch 2/1000
30/30 - 0s - loss: 0.4137 - accuracy: 0.7551
Epoch 3/1000
30/30 - 0s - loss: 0.4125 - accuracy: 0.7593
Epoch 4/1000
30/30 - 0s - loss: 0.4213 - accuracy: 0.7508
Epoch 5/1000
30/30 - 0s - loss: 0.4252 - accuracy: 0.7508
Epoch 6/1000
30/30 - 0s - loss: 0.4161 - accuracy: 0.7593
Epoch 7/1000
30/30 - 0s - loss: 0.4141 - accuracy: 0.7465
Epoch 8/1000
30/30 - 0s - loss: 0.4148 - accuracy: 0.7423
Epoch 9/1000
30/30 - 0s - loss: 0.4158 - accuracy: 0.7508
Epoch 10/1000
30/30 - 0s - loss: 0.4239 - accuracy: 0.7465
Epoch 11/1000
30/30 - 0s - loss: 0.4140 - accuracy: 0.7465
Epoch 12/1000
30/30 - 0s - loss: 0.4148 - accuracy: 0.7540
Epoch 13/1000
30/30 - 0s - loss: 0.4149 - accuracy: 0.7487
Epoch 14/1000
30/30 - 0s - loss: 0.4197 - accuracy: 0.7529
Epoch 15/1000
30/30 - 0s - loss: 0.4107 - accuracy: 0.7604
Epoch 16/1000
30/30 - 0s - loss: 0.4154 - accuracy: 0.7551
Epoch 17/1000
30/30 - 0s - loss: 0.4099 - accuracy: 0.7423
Epoch 

Epoch 140/1000
30/30 - 0s - loss: 0.4081 - accuracy: 0.7678
Epoch 141/1000
30/30 - 0s - loss: 0.4089 - accuracy: 0.7519
Epoch 142/1000
30/30 - 0s - loss: 0.4148 - accuracy: 0.7551
Epoch 143/1000
30/30 - 0s - loss: 0.4101 - accuracy: 0.7625
Epoch 144/1000
30/30 - 0s - loss: 0.4091 - accuracy: 0.7583
Epoch 145/1000
30/30 - 0s - loss: 0.4048 - accuracy: 0.7625
Epoch 146/1000
30/30 - 0s - loss: 0.4136 - accuracy: 0.7508
Epoch 147/1000
30/30 - 0s - loss: 0.4115 - accuracy: 0.7561
Epoch 148/1000
30/30 - 0s - loss: 0.4107 - accuracy: 0.7540
Epoch 149/1000
30/30 - 0s - loss: 0.4141 - accuracy: 0.7497
Epoch 150/1000
30/30 - 0s - loss: 0.4110 - accuracy: 0.7529
Epoch 151/1000
30/30 - 0s - loss: 0.4155 - accuracy: 0.7646
Epoch 152/1000
30/30 - 0s - loss: 0.4122 - accuracy: 0.7572
Epoch 153/1000
30/30 - 0s - loss: 0.4103 - accuracy: 0.7561
Epoch 154/1000
30/30 - 0s - loss: 0.4138 - accuracy: 0.7508
Epoch 155/1000
30/30 - 0s - loss: 0.4108 - accuracy: 0.7668
Epoch 156/1000
30/30 - 0s - loss: 0.4110

Epoch 277/1000
30/30 - 0s - loss: 0.4089 - accuracy: 0.7519
Epoch 278/1000
30/30 - 0s - loss: 0.4070 - accuracy: 0.7625
Epoch 279/1000
30/30 - 0s - loss: 0.4071 - accuracy: 0.7476
Epoch 280/1000
30/30 - 0s - loss: 0.4078 - accuracy: 0.7476
Epoch 281/1000
30/30 - 0s - loss: 0.4049 - accuracy: 0.7444
Epoch 282/1000
30/30 - 0s - loss: 0.4093 - accuracy: 0.7583
Epoch 283/1000
30/30 - 0s - loss: 0.4052 - accuracy: 0.7551
Epoch 284/1000
30/30 - 0s - loss: 0.4051 - accuracy: 0.7497
Epoch 285/1000
30/30 - 0s - loss: 0.4037 - accuracy: 0.7519
Epoch 286/1000
30/30 - 0s - loss: 0.4034 - accuracy: 0.7614
Epoch 287/1000
30/30 - 0s - loss: 0.4026 - accuracy: 0.7551
Epoch 288/1000
30/30 - 0s - loss: 0.4050 - accuracy: 0.7508
Epoch 289/1000
30/30 - 0s - loss: 0.4037 - accuracy: 0.7572
Epoch 290/1000
30/30 - 0s - loss: 0.4028 - accuracy: 0.7476
Epoch 291/1000
30/30 - 0s - loss: 0.4010 - accuracy: 0.7465
Epoch 292/1000
30/30 - 0s - loss: 0.4073 - accuracy: 0.7540
Epoch 293/1000
30/30 - 0s - loss: 0.4039

Epoch 414/1000
30/30 - 0s - loss: 0.3999 - accuracy: 0.7487
Epoch 415/1000
30/30 - 0s - loss: 0.4034 - accuracy: 0.7487
Epoch 416/1000
30/30 - 0s - loss: 0.4032 - accuracy: 0.7572
Epoch 417/1000
30/30 - 0s - loss: 0.4052 - accuracy: 0.7572
Epoch 418/1000
30/30 - 0s - loss: 0.4107 - accuracy: 0.7604
Epoch 419/1000
30/30 - 0s - loss: 0.4046 - accuracy: 0.7401
Epoch 420/1000
30/30 - 0s - loss: 0.4043 - accuracy: 0.7646
Epoch 421/1000
30/30 - 0s - loss: 0.4058 - accuracy: 0.7551
Epoch 422/1000
30/30 - 0s - loss: 0.3993 - accuracy: 0.7551
Epoch 423/1000
30/30 - 0s - loss: 0.4061 - accuracy: 0.7433
Epoch 424/1000
30/30 - 0s - loss: 0.4003 - accuracy: 0.7519
Epoch 425/1000
30/30 - 0s - loss: 0.4023 - accuracy: 0.7487
Epoch 426/1000
30/30 - 0s - loss: 0.4031 - accuracy: 0.7519
Epoch 427/1000
30/30 - 0s - loss: 0.4038 - accuracy: 0.7572
Epoch 428/1000
30/30 - 0s - loss: 0.4034 - accuracy: 0.7519
Epoch 429/1000
30/30 - 0s - loss: 0.4028 - accuracy: 0.7455
Epoch 430/1000
30/30 - 0s - loss: 0.4019

Epoch 551/1000
30/30 - 0s - loss: 0.3962 - accuracy: 0.7572
Epoch 552/1000
30/30 - 0s - loss: 0.3982 - accuracy: 0.7487
Epoch 553/1000
30/30 - 0s - loss: 0.3997 - accuracy: 0.7614
Epoch 554/1000
30/30 - 0s - loss: 0.3938 - accuracy: 0.7614
Epoch 555/1000
30/30 - 0s - loss: 0.3961 - accuracy: 0.7455
Epoch 556/1000
30/30 - 0s - loss: 0.3960 - accuracy: 0.7593
Epoch 557/1000
30/30 - 0s - loss: 0.3953 - accuracy: 0.7593
Epoch 558/1000
30/30 - 0s - loss: 0.4009 - accuracy: 0.7380
Epoch 559/1000
30/30 - 0s - loss: 0.3992 - accuracy: 0.7540
Epoch 560/1000
30/30 - 0s - loss: 0.4023 - accuracy: 0.7583
Epoch 561/1000
30/30 - 0s - loss: 0.4088 - accuracy: 0.7646
Epoch 562/1000
30/30 - 0s - loss: 0.4084 - accuracy: 0.7529
Epoch 563/1000
30/30 - 0s - loss: 0.4016 - accuracy: 0.7625
Epoch 564/1000
30/30 - 0s - loss: 0.4023 - accuracy: 0.7657
Epoch 565/1000
30/30 - 0s - loss: 0.4060 - accuracy: 0.7529
Epoch 566/1000
30/30 - 0s - loss: 0.4006 - accuracy: 0.7540
Epoch 567/1000
30/30 - 0s - loss: 0.3997

Epoch 688/1000
30/30 - 0s - loss: 0.3912 - accuracy: 0.7529
Epoch 689/1000
30/30 - 0s - loss: 0.3969 - accuracy: 0.7604
Epoch 690/1000
30/30 - 0s - loss: 0.3955 - accuracy: 0.7604
Epoch 691/1000
30/30 - 0s - loss: 0.3978 - accuracy: 0.7614
Epoch 692/1000
30/30 - 0s - loss: 0.3920 - accuracy: 0.7636
Epoch 693/1000
30/30 - 0s - loss: 0.3944 - accuracy: 0.7455
Epoch 694/1000
30/30 - 0s - loss: 0.3916 - accuracy: 0.7476
Epoch 695/1000
30/30 - 0s - loss: 0.3923 - accuracy: 0.7519
Epoch 696/1000
30/30 - 0s - loss: 0.3903 - accuracy: 0.7625
Epoch 697/1000
30/30 - 0s - loss: 0.3930 - accuracy: 0.7636
Epoch 698/1000
30/30 - 0s - loss: 0.3918 - accuracy: 0.7678
Epoch 699/1000
30/30 - 0s - loss: 0.3924 - accuracy: 0.7625
Epoch 700/1000
30/30 - 0s - loss: 0.3924 - accuracy: 0.7561
Epoch 701/1000
30/30 - 0s - loss: 0.3916 - accuracy: 0.7551
Epoch 702/1000
30/30 - 0s - loss: 0.3927 - accuracy: 0.7497
Epoch 703/1000
30/30 - 0s - loss: 0.3923 - accuracy: 0.7465
Epoch 704/1000
30/30 - 0s - loss: 0.3944

Epoch 825/1000
30/30 - 0s - loss: 0.3918 - accuracy: 0.7614
Epoch 826/1000
30/30 - 0s - loss: 0.3908 - accuracy: 0.7625
Epoch 827/1000
30/30 - 0s - loss: 0.3884 - accuracy: 0.7444
Epoch 828/1000
30/30 - 0s - loss: 0.3896 - accuracy: 0.7529
Epoch 829/1000
30/30 - 0s - loss: 0.3890 - accuracy: 0.7604
Epoch 830/1000
30/30 - 0s - loss: 0.3889 - accuracy: 0.7476
Epoch 831/1000
30/30 - 0s - loss: 0.3877 - accuracy: 0.7636
Epoch 832/1000
30/30 - 0s - loss: 0.3860 - accuracy: 0.7551
Epoch 833/1000
30/30 - 0s - loss: 0.4016 - accuracy: 0.7551
Epoch 834/1000
30/30 - 0s - loss: 0.4029 - accuracy: 0.7487
Epoch 835/1000
30/30 - 0s - loss: 0.3973 - accuracy: 0.7583
Epoch 836/1000
30/30 - 0s - loss: 0.3920 - accuracy: 0.7678
Epoch 837/1000
30/30 - 0s - loss: 0.3899 - accuracy: 0.7614
Epoch 838/1000
30/30 - 0s - loss: 0.3894 - accuracy: 0.7604
Epoch 839/1000
30/30 - 0s - loss: 0.3902 - accuracy: 0.7572
Epoch 840/1000
30/30 - 0s - loss: 0.3893 - accuracy: 0.7529
Epoch 841/1000
30/30 - 0s - loss: 0.3916

Epoch 962/1000
30/30 - 0s - loss: 0.3873 - accuracy: 0.7540
Epoch 963/1000
30/30 - 0s - loss: 0.3891 - accuracy: 0.7614
Epoch 964/1000
30/30 - 0s - loss: 0.3900 - accuracy: 0.7593
Epoch 965/1000
30/30 - 0s - loss: 0.3889 - accuracy: 0.7519
Epoch 966/1000
30/30 - 0s - loss: 0.3862 - accuracy: 0.7604
Epoch 967/1000
30/30 - 0s - loss: 0.3860 - accuracy: 0.7668
Epoch 968/1000
30/30 - 0s - loss: 0.3865 - accuracy: 0.7583
Epoch 969/1000
30/30 - 0s - loss: 0.3860 - accuracy: 0.7614
Epoch 970/1000
30/30 - 0s - loss: 0.3875 - accuracy: 0.7625
Epoch 971/1000
30/30 - 0s - loss: 0.3873 - accuracy: 0.7593
Epoch 972/1000
30/30 - 0s - loss: 0.3834 - accuracy: 0.7561
Epoch 973/1000
30/30 - 0s - loss: 0.3857 - accuracy: 0.7593
Epoch 974/1000
30/30 - 0s - loss: 0.3848 - accuracy: 0.7476
Epoch 975/1000
30/30 - 0s - loss: 0.3855 - accuracy: 0.7625
Epoch 976/1000
30/30 - 0s - loss: 0.3862 - accuracy: 0.7508
Epoch 977/1000
30/30 - 0s - loss: 0.3880 - accuracy: 0.7519
Epoch 978/1000
30/30 - 0s - loss: 0.3861

In [85]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test_categorical, verbose=2)
print(
    f"Normal Neural Network - Loss: {model_loss}, Accuracy: {model_accuracy}")

4/4 - 0s - loss: 2.8108 - accuracy: 0.5810
Normal Neural Network - Loss: 2.810845375061035, Accuracy: 0.5809524059295654


In [80]:
encoded_predictions = model.predict_classes(X_test_scaled[:10])
print(encoded_predictions)

[3 3 3 3 3 3 3 3 2 3]


In [81]:
print(f'actual {y_test.head(10)} prediction{encoded_predictions[:10]}')

actual 157    3
443    3
728    3
515    3
819    3
90     2
958    1
624    3
513    3
280    2
Name: grade, dtype: int64 prediction[3 3 3 3 3 3 3 3 2 3]


In [82]:
print(X_test_scaled)

[[-1.15408598  1.0219511   0.31362473  2.08734275  1.57773449]
 [-0.19166437 -1.39115557  1.02154208 -0.22854718 -0.14693686]
 [-0.19166437  0.21758221 -0.39429263 -1.00051049 -0.14693686]
 [-1.15408598 -1.39115557 -1.81012733 -0.22854718 -0.14693686]
 [ 0.77075724 -0.58678668  1.02154208 -1.00051049  0.71539881]
 [-0.19166437 -0.58678668  0.31362473  0.54341613 -0.14693686]
 [-1.15408598  0.21758221  1.02154208  0.54341613 -1.8716082 ]
 [ 0.77075724  0.21758221 -1.81012733  0.54341613  0.71539881]
 [-1.15408598  0.21758221  1.02154208  1.31537944  0.71539881]
 [ 1.73317885  0.21758221  1.02154208  1.31537944  0.71539881]
 [ 0.77075724 -0.58678668 -1.81012733  0.54341613  0.71539881]
 [-1.15408598  1.0219511   1.02154208  2.08734275  1.57773449]
 [-0.19166437  0.21758221  0.31362473 -0.22854718 -1.00927253]
 [-0.19166437  1.0219511  -1.10220998 -0.22854718 -0.14693686]
 [-0.19166437  0.21758221  0.31362473 -0.22854718 -0.14693686]
 [ 1.73317885  0.21758221 -1.81012733 -1.00051049 -1.00

In [ ]:
# Save the model
model.save('deeplearning.h5')